Corpus Translate (Fiqa example)
vTuanpham/Large_dataset_translator pull request #7
Opened 2024-07-27 13:25 UTC by Abdulkader-Saoud

Added a config for corpus translation for the BeIR/fiqa dataset.

I’m not entirely sure if this is the optimal solution, feel free to reject.

2024-07-27 16:34 UTC, vTuanpham commented
Hey @Abdulkader-Saoud, thanks for the first pr to this repo!. I will review the pr and merge, thank you for your contribution!

2024-07-27 16:42 UTC, vTuanpham requested changes
I have review the pr, i will merge as soon as the review request is done. Thanks again for your contribution!

2024-07-27 16:42 UTC, vTuanpham commented on configs/corpus_config.py
> +    system_prompt: str
I don't really think a Corpus dataset will need a system_prompt attr, so you can remove this

2024-07-27 16:42 UTC, vTuanpham commented on examples/Fiqa/FiqaParser.py
> +        system_prompts = [
No need for the system_prompts here neither since the dataset is for continual pre-training and no fine-tuning for assistant related task.

2024-07-27 16:42 UTC, vTuanpham commented on examples/Fiqa/FiqaParser.py
> +    alpaca_cleaned_parser.save
Change from "alpaca_cleaned_parser" to "fiqa_parser" and we all good!

2024-07-27 21:45 UTC, Abdulkader-Saoud commented
Thank you for the feedback and pointing out the mistakes. 
I've made the changes. I hope the latest commit meets your requirements. Thank you for maintaining this helpful repository!

2024-07-28 01:16 UTC, vTuanpham approved these changes

2024-07-28 01:17 UTC, merged